spring:
  application:
    name: subd


  datasource:
    url: jdbc:postgresql://localhost:5432/bakery
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 9876

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    enabled: true

jwt:
  secret: XLxE0RzQMivgfxdRafz8TaokC+owrCoNBM+PRUwBx1ivl/+tMUz6PyupQxF9ctjpxZo4Y2jyx0mTKxYv/ho3mg==
  expirationMs: 3600000